# Generated by Django 2.2.13 on 2020-06-24 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mainlocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainLocationName', models.CharField(max_length=200, unique=True)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sublocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('SubLocationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Mainlocation')),
            ],
        ),
    ]
