# Generated by Django 2.2.13 on 2020-06-24 19:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublocation',
            name='MainLocationName',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='location.Mainlocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sublocation',
            name='SubLocationName',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
