# Generated by Django 2.2.13 on 2020-07-03 19:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propertymeta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyID', models.CharField(max_length=255, unique=True)),
                ('PropertyTitle', models.CharField(max_length=500)),
                ('PropertyTitleMeta', models.CharField(max_length=500)),
                ('YearBuilt', models.DateField()),
                ('Price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('Floor', models.IntegerField()),
                ('Area', models.IntegerField()),
                ('BedRoom', models.IntegerField(blank=True, null=True)),
                ('BathRoom', models.IntegerField(blank=True, null=True)),
                ('Video', models.URLField(blank=True, max_length=500, null=True)),
                ('About', models.TextField()),
                ('Address', models.TextField()),
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Status', models.BooleanField(default=True)),
                ('propertyaminity', models.CharField(blank=True, max_length=500, null=True)),
                ('CreatedOn', models.DateField(default=datetime.datetime.now)),
                ('Furnishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertymeta.Furnishing')),
                ('MainLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertymeta.Mainlocation')),
                ('PropertyType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertymeta.PropertyType')),
                ('RentBuy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertymeta.RentBuy')),
                ('SubLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertymeta.Sublocation')),
                ('TimePeriod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertymeta.TimePeriod')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyNearby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NearbyType', models.CharField(max_length=200)),
                ('Distance', models.CharField(max_length=200)),
                ('Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyImageType', models.CharField(max_length=200)),
                ('PropertyImage', models.ImageField(upload_to='PropertyAsset')),
                ('Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
        ),
    ]
