# Generated by Django 2.2.13 on 2020-06-26 19:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyTitle', models.CharField(max_length=500)),
                ('PropertyTitleMeta', models.CharField(max_length=500)),
                ('RentBuy', models.IntegerField()),
                ('PropertyType', models.IntegerField()),
                ('TimePeriod', models.IntegerField()),
                ('Furnishing', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('Floor', models.IntegerField()),
                ('Area', models.IntegerField()),
                ('BedRoom', models.IntegerField()),
                ('Video', models.URLField(blank=True, max_length=500, null=True)),
                ('MainLocation', models.IntegerField()),
                ('SubLocation', models.IntegerField()),
                ('About', models.TextField()),
                ('Status', models.BooleanField(default=True)),
                ('CreatedOn', models.DateField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PropertyImage', models.ImageField(upload_to='PropertyAsset')),
                ('Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAminities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aminity', models.CharField(max_length=500)),
                ('Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
    ]
