# Generated by Django 2.2.13 on 2020-06-26 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_propertyaminities_propertyimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Furnishing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Furnishing'),
        ),
        migrations.AlterField(
            model_name='property',
            name='MainLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Mainlocation'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PropertyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.PropertyType'),
        ),
        migrations.AlterField(
            model_name='property',
            name='RentBuy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.RentBuy'),
        ),
        migrations.AlterField(
            model_name='property',
            name='SubLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Sublocation'),
        ),
        migrations.AlterField(
            model_name='property',
            name='TimePeriod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.TimePeriod'),
        ),
    ]
