# Generated by Django 2.2.13 on 2020-06-26 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20200627_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='BathRoom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='PropertyID',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='YearBuilt',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='PropertyImageType',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='BedRoom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
