# Generated by Django 2.2.13 on 2020-06-26 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20200627_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyaminities',
            name='Aminity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='PropertyImageType',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='PropertyNearby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NearbyType', models.CharField(max_length=200)),
                ('Distance', models.ImageField(upload_to='PropertyAsset')),
                ('Property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
    ]
