# Generated by Django 2.2.13 on 2020-06-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20200624_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='Name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
