# Generated by Django 2.2.13 on 2020-06-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20200625_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
