# Generated by Django 2.2.13 on 2020-06-28 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20200625_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createagency',
            name='PaymentExpiry',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
