# Generated by Django 2.2.13 on 2020-06-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20200629_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createagency',
            name='PaymentExpiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
